### ISSUE TITLE
What are file managers?

### ISSUE THREAD

**Issue by shmup** [rothgar/awesome-tuis#101]
They're listed under:

`Dashboards`

` Misc`

`Productivity`

I vote for choosing 1 category.

**Comment by rothgar** [comment]
It grew organically and some file managers do multiple things. It might make sense to make a file managers category and put them all in there. Otherwise I would probably put it under productivity.

**Comment by shmup** [comment]
Makes sense re: organically growing

Handle it however you want (if at all!), I noticed you're not too category heavy so the _new_ category is only if it makes sense to you :)
