### ISSUE TITLE
Gotop under new(ish) management

### ISSUE THREAD

**Issue by xxxserxxx** [rothgar/awesome-tuis#11]
Would you mind changing the link for gotop to https://github.com/xxxserxxx/gotop?  Caleb is no longer developing it, and his project links to mine at the top; Arch, Nix, and Homebrew are also pulling from the new repo.  I've been maintaining (and developing) the project since February 2020.

Thanks!

**Comment by octoshrimpy** [comment]
taken care of in https://github.com/rothgar/awesome-tuis/pull/21
