### ISSUE TITLE
Add pictures for each program

### ISSUE THREAD

**Issue by bphd** [rothgar/awesome-tuis#160]

**Comment by rothgar** [comment]
I don't think that's feasible for all of these apps and it would make the readme extremely long and harder to read. If you have any examples of other readmes that have this many screenshots?

**Comment by bphd** [comment]
You can hide them with \<details\>

> I don't think that's feasible for all of these apps and it would make the readme extremely long and harder to read. If you have any examples of other readmes that have this many screenshots?

**Comment by bphd** [comment]
It's done!? What speed! Give link to result

**Comment by rothgar** [comment]
If you have ideas on how to get screenshots. Many of the project repos don't have screenshots. If you know how to automate screenshots it would be even better.

**Comment by rothgar** [comment]
I'm not sure that would add a lot of benefit for the amount of work it would require. I think adding a collapsible details with a screenshot would make the readme harder to skim/read and screenshot commands would need to be tracked for each command which would add more maintenance
