### ISSUE TITLE
Add IconicFonts

### ISSUE THREAD

**Issue by mdSlash** [rothgar/awesome-tuis#234]
Hi @rothgar, I’ve created patched fonts with over 60,000 icons specifically for TUI projects. Can I submit a pull request to include [IconicFonts](https://github.com/iconicFonts/iconic-fonts) repository in Awesome TUIs list?

**Comment by rothgar** [comment]
Yes, that seems fine. It's probably a Misc item. Please put it alphabetically in the section.

**Comment by mdSlash** [comment]
Thanks, I will submit a PR.
