### ISSUE TITLE
dug

### ISSUE THREAD

**Issue by MattInternet** [rothgar/awesome-tuis#56]
dug is a DNS propagation checker with a simple TUI. Might count for this list? https://github.com/unfrl/dug

**Comment by rothgar** [comment]
This looks really neat. I can't tell from the gifs if the output is just special formatting or interactive. If it's just formatting output I don't think I'll add it to the list but I might install it on my system anyway.

**Comment by MattInternet** [comment]
Ah yeah it is just formatting, not interactive. Thanks so much for this repo though! Discovering `dive` was super fun!
